### ISSUE TITLE
Question : Can it work with other documents type supported by mupdf ?

### ISSUE THREAD

**Issue by Miaourt** [andytango/mupdf-js#2]
Hello Andrew, thanks for your work there !
Sadly can't try right now, but wondered if you tried your library with other documents, MuPDF advertise support for "PDF, XPS, OpenXPS, CBZ, EPUB, and FictionBook 2" files so I was hoping maybe it would work ?
Thanks !

**Comment by andytango** [comment]
It hasn't been tested with these other formats but you are welcome to try @Miaourt  

Closing as this issue is old.
