### ISSUE TITLE
Feature Request: Expose more functions from MuPDF

### ISSUE THREAD

**Issue by ZZYSonny** [andytango/mupdf-js#5]
The MuPDF WASM demo on the official site exposes more functions from the WASM. `pageTextJSON` can be used to generate a better text selection layer and the second function is essential for searching text. Could you please add these functions to MuPDF-js? 
```js
	mupdf.pageTextJSON = Module.cwrap('pageText', 'string', ['number', 'number', 'number']);
	mupdf.searchJSON = Module.cwrap('search', 'string', ['number', 'number', 'number', 'string']);
```

**Comment by andytango** [comment]
This is now available in v1.1.0 - thanks again for your PR @anthrax63
